stereo_cameras:
  - name: front_stereo_camera
    left: /front_stereo_camera/left/image_raw
    left_camera_info: /front_stereo_camera/left/camera_info
    right: /front_stereo_camera/right/image_raw
    right_camera_info: /front_stereo_camera/right/camera_info
